language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
install:
  pip install codecov
# command to run tests
script: nosetests --with-coverage test_pretty_numbers.py
after_success:
    codecov
