language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.8"
install:
  pip install codecov
# command to run tests
script: nosetests --with-coverage test_pretty_numbers.py
after_success:
    codecov
