from typing import Any, Sequence, Set

def getPrettyTextFromSet(frames: Set[int]) -> str: ...
def getPrettyTextFromNumbers(frames: Sequence[int]) -> str: ...
def getPrettyNumbersText(list_of_strings: Sequence[Any]) -> str: ...
