jobs:
  test:
    executor: python/default
    steps:
      - checkout
      - run:
          command: |
              pip install tox tox-pyenv
              pyenv versions
              pyenv local 3.4.3 3.5.10 3.7.11 3.8.12
              tox
          name: Test it
orbs:
  python: circleci/python@1.0.0
version: 2.1
workflows:
  main:
    jobs:
      - test
