version: 2.1
orbs:
  codecov: codecov/codecov@3.2.2
  python: circleci/python@1.5.0

jobs:
  test_py36:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          command: |
            pip install poetry
            poetry install
            poetry run nosetests --with-coverage test_pretty_numbers.py
          name: Test it
  test_py37:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: |
            pip install poetry
            poetry install
            poetry run nosetests --with-coverage test_pretty_numbers.py
          name: Test it
  test_py38_main:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          command: |
            pip install poetry
            poetry install
            poetry run nosetests --with-coverage test_pretty_numbers.py --cover-xml
          name: Test it
      - store_artifacts:
          path: coverage.xml
      - codecov/upload

  test_py39:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          command: |
            pip install poetry
            poetry install
            poetry run nosetests --with-coverage test_pretty_numbers.py
          name: Test it

  black:
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          command: |
            poetry run black --check *.py


workflows:
  main:
    jobs:
      - test_py36
      - test_py37
      - test_py38_main
      - test_py39
