version: 2.1
orbs:
  codecov: codecov/codecov@3.2.2
  python: circleci/python@1.5.0

jobs:
  test_py38_main:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          command: |
            poetry run nosetests --with-coverage test_pretty_numbers.py --cover-xml
          name: Test it
      - store_artifacts:
          path: coverage.xml
      - codecov/upload

  test_py39:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          command: |
            poetry run nosetests test_pretty_numbers.py
  pylint:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          command: |
            poetry run pylint *.py
  black:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          command: |
            poetry run black --check *.py

  mypy:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          command: |
            poetry run mypy --strict pretty_numbers.py
            poetry run mypy --strict test_pretty_numbers.py
  test_publish:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          command: |
            python setup.py sdist bdist_wheel
            poetry run twine check dist/*
            poetry run twine upload -u __token__ -p $TEST_TWINE_PASS --repository-url https://test.pypi.org/legacy/ dist/*
  real_publish:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          command: |
            python setup.py sdist bdist_wheel
            poetry run twine check dist/*
            poetry run twine upload -u __token__ -p $TWINE_PASSWORD dist/*

workflows:
  main:
    jobs:
      - test_py38_main
      - test_py39
      - black
      - mypy
      - pylint
      - test_publish:
          requires:
            - test_py38_main
            - test_py39
            - black
            - mypy
            - pylint
          filters:
            branches:
              only:
                - main
      - real_publish_approval:
          requires:
            - test_publish
          type: approval
      - real_publish:
          requires:
            - real_publish_approval
