version: 2

jobs:
  test_py36:
    docker:
      - image: circleci/python:3.6
    executor: python/default
    steps:
      - checkout
      - run:
          command: |
              pip install poetry
              poetry run nosetests --with-coverage test_pretty_numbers.py
          name: Test it


workflows:
  main:
    jobs:
      - test_py36
