version: 2.1
orbs:
  codecov: codecov/codecov@3.2.2
  python: circleci/python@1.5.0

jobs:
  test_py38_main:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          command: |
            poetry run nosetests --with-coverage pretty_numbers --cover-xml
          name: Test it
      - store_artifacts:
          path: coverage.xml
      - codecov/upload

  test_py39:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          command: |
            poetry run nosetests pretty_numbers
  pylint:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          command: |
            poetry run pylint pretty_numbers
  black:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          command: |
            poetry run black --check pretty_numbers

  mypy:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          command: |
            poetry run mypy --strict pretty_numbers
  test_publish:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Publish to test pypi
          command: |
            poetry build
            poetry config repositories.test-pypi https://test.pypi.org/legacy/
            poetry config pypi-token.test-pypi $TEST_PYPI_TOKEN
            poetry publish -r test-pypi
  real_publish:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Publish to PyPi
          command: |
            poetry build
            poetry config pypi-token.pypi $PYPI_TOKEN
            poetry publish

workflows:
  main:
    jobs:
      - test_py38_main
      - test_py39
      - black
      - mypy
      - pylint
      - test_publish:
          requires:
            - test_py38_main
            - test_py39
            - black
            - mypy
            - pylint
          filters:
            branches:
              only:
                - main
      - real_publish_approval:
          requires:
            - test_publish
          type: approval
      - real_publish:
          requires:
            - real_publish_approval
